version: "3"
services:
  web:
    build: . 
    ports:
      - "8000:8000"
    depends_on:
      - "db"
    command: ["./wait-for-mysql.sh"]
  db:
    image: mysql:latest
    environment: 
      - MYSQL_ROOT_PASSWORD=sts1551@IWO
    # you don't need to publish db ports to outside; don't do it 

